apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lhxlfqmcq-nodejs 
  janus-idp.io/tekton: lhxlfqmcq-nodejs
  backstage.io/kubernetes-id: lhxlfqmcq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lhxlfqmcq-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  